apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: ecommerce
    tier: database
spec:
  selector:
    matchLabels:
      app: ecommerce
      tier: database
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        app: ecommerce
        tier: database
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: mongodb-configmap
        - secretRef:
            name: mongodb-secret
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
