apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: ecommerce
spec:
  type: ClusterIP
  selector:
    app: ecommerce
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
