apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: ecommerce
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
      tier: frontend
  template:
    metadata:
      labels:
        app: ecommerce
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: frontend-configmap
