apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: ecommerce
spec:
  type: ClusterIP
  selector:
    app: ecommerce
    tier: backend
  ports:
    - port: 3000
      targetPort: 3000
