apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  labels:
    app: ecommerce
data:
  APP_ENV: production
  LOG_LEVEL: debug
  API_VERSION: v1
  MONGO_URI: "mongodb://mongo-service:27017/ecommerce"
