apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: ecommerce
    tier: messaging
spec:
  ports:
    - port: 5672
    - port: 15672
  selector:
    app: ecommerce
    tier: messaging
